# Cargo configuration for embedded Python and USD
[env]
# Point PyO3 to our embedded Python (absolute paths needed for PyO3 build)
PYO3_PYTHON = "/Users/brian/nodle/nodle/vendor/python-runtime/python/bin/python3"
PYO3_PYTHON_VERSION = "3.9"
PYTHONPATH = "/Users/brian/nodle/nodle/vendor/usd/lib/python:/Users/brian/nodle/nodle/vendor/python-runtime/python/lib/python3.9/site-packages"

# USD paths
NODLE_USD_ROOT = "/Users/brian/nodle/nodle/vendor/usd"
USD_INSTALL_ROOT = "/Users/brian/nodle/nodle/vendor/usd"
PATH = "/Users/brian/nodle/nodle/vendor/usd/bin:/usr/bin:/bin"

# Library path for embedded Python and USD
DYLD_LIBRARY_PATH = "/Users/brian/nodle/nodle/vendor/usd/lib:/Users/brian/nodle/nodle/vendor/python-runtime/python/lib"
LD_LIBRARY_PATH = "/Users/brian/nodle/nodle/vendor/usd/lib:/Users/brian/nodle/nodle/vendor/python-runtime/python/lib"

[build]
# Link against our embedded Python library and USD
rustflags = [
    "-L", "/Users/brian/nodle/nodle/vendor/python-runtime/python/lib",
    "-L", "/Users/brian/nodle/nodle/vendor/usd/lib",
    "-Wl,-rpath,/Users/brian/nodle/nodle/vendor/python-runtime/python/lib",
    "-Wl,-rpath,/Users/brian/nodle/nodle/vendor/usd/lib"
]
