# Cargo configuration for embedded Python and USD
[env]
# Point PyO3 to our embedded Python
PYO3_PYTHON = "/Users/brian/nodle/nodle/vendor/python-runtime/python/bin/python3"
PYO3_PYTHON_VERSION = "3.9"
PYTHONPATH = "./vendor/python-runtime/python/lib/python3.9/site-packages:./vendor/python-runtime/python/lib/python3.9"
PYTHONHOME = "./vendor/python-runtime/python"

# USD paths
NODLE_USD_ROOT = "./vendor/python-runtime/python"
USD_INSTALL_ROOT = "./vendor/python-runtime/python"

# Library path for embedded Python
DYLD_LIBRARY_PATH = "./vendor/python-runtime/python/lib"
LD_LIBRARY_PATH = "./vendor/python-runtime/python/lib"

[build]
# Link against our embedded Python library
rustflags = [
    "-L", "./vendor/python-runtime/python/lib",
    "-Wl,-rpath,./vendor/python-runtime/python/lib"
]
